### ISSUE TITLE
As a student, I want to be able to add a category or tag to the task list that I am importing

### ISSUE THREAD

**Issue by btzy** [CS2103-AY1819S1-W17-4/main#22]
... so that the tasks being imported can be grouped with a category or tag of my choice.  (This is useful if there is already a category or tag of the same name.)

**Comment by ranaldmiao** [comment]
Not implemented.
However, the creator of the task list can pre-tag these tasks before exporting it.
Then, all the other users that import the task will already have those tags as well.
