### ISSUE TITLE
As a student, I want to be able to export a subset of tasks in calendar(.ics) format

### ISSUE THREAD

**Issue by sidhant007** [CS2103-AY1819S1-W17-4/main#23]
...so that I can have the tasks/deadlines on other devices (ex. android phone) as well.

**Comment by ranaldmiao** [comment]
@sijie123 Is this in the roadmap for v2.0?

**Comment by sijie123** [comment]
Yes, will be in the roadmap for v2.0.
Currently, we will only support csv format.
