### ISSUE TITLE
Allow any character for task name (not just alphanumeric characters and spaces)

### ISSUE THREAD

**Issue by btzy** [CS2103-AY1819S1-W17-4/main#259]
There is no need to restrict to alphanumeric characters any more.  Also, see issue #232.

**Comment by ranaldmiao** [comment]
I am not in favour of this change as this might interfere in the XML storage.

For instance, what if the task is named </Task>

**Comment by sijie123** [comment]
Sorry for the late reply.
I am not in favour of this change either, given the short amount of time we have remaining.
