### ISSUE TITLE
Filter/search by 'and'/'or' composite predicates

### ISSUE THREAD

**Issue by btzy** [CS2103-AY1819S1-W17-4/main#36]
- Support 'and' and 'or' operations, e.g. "tag>CS2101 or tag>CS2103T"

**Comment by sidhant007** [comment]
Remark - Incase time does not permit this implementation, a filter on an already filtered list being applied also serves the use case from the users perspective.

**Comment by btzy** [comment]
@sidhant007 Filter on an already filtered list will only solve 'and', but not 'or'.
